### PR TITLE
Fix: 230 as an inspector i want the label inspection form to include the guaranteed analysis title

### LINKED ISSUE #230: Guaranteed analysis title

### PR DESCRIPTION
**Pull request by Youllou**
Fix #230
removed guaranteed analysis from Fertiliser section
added 2 sections Guarenteed analysis fr and en that have 2 inputs : title and nutrients

### CODE REVIEW

File: src/interfaces/Inspection.ts [hunk 1]
```diff
@@ -141,6 +146,13 @@ export const createDefaultInspection = (): Inspection => ({
     fr: [createDefaultSpecification()],
   },
   first_aid: { en: [], fr: [] },
-  guaranteed_analysis: [createDefaultNamedValue()],
+  guaranteed_analysis_fr: {
```
Comment (k-allagbe) [inline src/interfaces/Inspection.ts:149]: Tested with:

granulaine

Received this from `post /inspections`:
```json
{
	"guaranteed_analysis": {
		"en": [
			{
				"edited": false,
				"name": "Total nitrogen (N)",
				"unit": "%",
				"value": 10
			},
			{
				"edited": false,
				"name": "Soluble potash (K2O)",
				"unit": "%",
				"value": 4
			},
			{
				"edited": false,
				"name": "Organic matter",
				"unit": "%",
				"value": 61.5
			},
			{
				"edited": false,
				"name": "Maximum moisture content",
				"unit": "%",
				"value": 14.8
			}
		],
		"fr": [
			{
				"edited": false,
				"name": "Azote totale",
				"unit": "%",
				"value": 10
			},
			{
				"edited": false,
				"name": "Potasse soluble",
				"unit": "%",
				"value": 4
			},
			{
				"edited": false,
				"name": "Matière organique",
				"unit": "%",
				"value": 61.5
			},
			{
				"edited": false,
				"name": "Teneur maximum en humidité",
				"unit": "%",
				"value": 14.8
			}
		],
		"is_minimal": null,
		"title": "Guaranteed minimum analysis",
		"titre": "Analyse minimum garantie"
	}
}
```

Page showed:
image

**Review by k-allagbe — APPROVED** [review]
